services:
  - type: web
    name: smart-planner-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-planner-db
          property: connectionString
      - key: BREVO_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false

databases:
  - name: smart-planner-db
    plan: free